### ISSUE TITLE
Score on the Leaderboards(Open the door) Is incorrect

### ISSUE THREAD

**Issue by HappyBerrysBoy** [autonity/autonity#962] opened 2024-03-20 02:29 UTC
### Description

The "Open the door" section of LeaderBoard is counting points incorrectly.
Username "validatorvn" is doubling his score every day.
When I checked that, username "validatorvn" is registered twice on the validator and PnL. 

Please check and correct.
(Note: The "hbb | Uncommon Lab" who reported on Discord is me.)

![image](https://github.com/autonity/autonity/assets/7401650/6f7687fa-39eb-4d70-ad2d-9f3d1b5f2a0c)

...

### System Information

---

### How to Reproduce

---

### Expected Behaviour

Earn 50 points every day (if operating normally)

...

### Actual Behaviour

One user get double points

...

**Comment by cmjc** [comment] 2024-03-20 09:22
Hi @HappyBerrysBoy - this is a known issue that has been caused by a duplicate registration to the game by the user.  This is a known issue and is being tracked for resolution in this Autonity Discord Ticket:  https://discord.com/channels/753937111781998605/1219937831145963570.

This is a Piccadilly Circus Games and not an AGC issue, so closing this here.

**Closed by cmjc** 2024-03-20 09:22 UTC
Labels: type:bug, triage, piccadilly-circus
