### ISSUE TITLE
Validate enodes on Autonity contract update

### ISSUE THREAD

**Issue by JekaMas** [autonity/autonity#487] opened 2020-03-26 10:53 UTC
https://github.com/clearmatics/autonity/pull/484 showed us that we need to validate somehow if a user's data is a correct enode or not.

We can:
1. Use something like regex validator https://github.com/gnidan/solregex
2. Add a precompiled contract https://medium.com/@rbkhmrcr/precompiles-solidity-e5d29bd428c4 and validate enode on Autonity side.

For me, the second is better because we could not only validate format but also validate if the address, pubkey and hash are correct in terms of cryptography which could be difficult of not impossible at all in Solidity code.

**Comment by piersy** [comment] 2020-03-26 11:13
@JekaMas This ticket doesn't let me know what the problem is. There is the reference to #484 but there is no mention in that or the associated ticket about validating enodes.

Could you update the ticket explaining why we need to validate an enode and what is meant by validating an enode?

**Comment by yazzaoui** [comment] 2020-03-26 21:46
I guess it's about verifying if the supplied enode has a correct format, see : https://github.com/ethereum/wiki/wiki/enode-url-format .

I think the priority is to make sure layer 1 is resilient enough and can support bad enodes, treat them as error cases, and then the verification wouldn't be needed but nice to have.

**Comment by JekaMas** [comment] 2020-03-27 08:22
I think I can add verification in 3-4 days. It's up to you to decide.

**Comment by piersy** [comment] 2020-03-30 08:57
@yazzaoui @JekaMas 
I'm still not clear on why we would need to validate an enode. #484 was about fixing consensus when an invalid enode is added, and it has been merged. So I'm wondering what other problems now require us to validate enodes?

**Comment by JekaMas** [comment] 2020-03-30 11:31
It always better to check and validate then deal with incorrect data. That's why things like debit card number are validated on each application level: frontend, backend, db.

**Comment by piersy** [comment] 2020-03-30 11:50
> It always better to check and validate then deal with incorrect data.

Ahh, so this would be another way of solving #451 right?

**Comment by JekaMas** [comment] 2020-03-30 12:01
I think so. Also this solution will provide to the client a meaningful error and cancel the transaction that will return to the user some gas also.

**Comment by piersy** [comment] 2020-03-30 13:51
@JekaMas So will we revert the fix from #484 when this ticket is done, so that we have just one place in the code that will deal with enforcing enode correctness?

**Comment by JekaMas** [comment] 2020-03-30 14:00
If it completely covers all the cases from #484, can be implemented, uses reasonable amount of gas than I think so.

**Comment by yazzaoui** [comment] 2020-03-30 18:42
We have to keep in mind that one of the Autonity Contract goal is to be as simple as possible and hide the complexity in layer 1. I'm thinking about someone creating its own contract and forgetting about the enode check, the client should treat a bad enode as an error case and ignore it.

**Comment by JekaMas** [comment] 2020-03-30 19:07
It'd be a problem of whole system if the contract will be spoiled with incorrect enodes.
Even more clients will call us and ask why successfully added enode doesn't work at all. And it's the cost of the support and also bad user experience.

**Comment by JekaMas** [comment] 2020-03-30 20:09
@yazzaoui here is the draft how it could be https://github.com/clearmatics/autonity/pull/492

**Closed** 2022-04-07 13:20 UTC
