### ISSUE TITLE
Panic with fatal: morestack on g0

### ISSUE THREAD

**Issue by Dedenwrg** [autonity/autonity#914] opened 2023-12-26 15:29 UTC
autonity  | INFO [12-26|14:05:57.045] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.047] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.049] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.050] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.050] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.054] Committed block                          hash=83190f..432eef height=1,609,611
autonity  | INFO [12-26|14:05:57.054] Imported new chain segment               blocks=1    txs=41    mgas=0.870    elapsed=7.589ms   mgasps=114.676 number=1,609,611 hash=83190f..432eef     dirty=119.56MiB
autonity  | INFO [12-26|14:05:57.060] Preparing new block proposal             number=1,609,612 sealhash=81ab50..4c3789 uncles=0 txs=33    gas=777,430   fees=0.043692036     elapsed=5.0    75ms
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
autonity  | fatal error: runtime·unlock: lock count
fatal: morestack on g0
autonity  | SIGTRAP: trace trap
autonity  | PC=0x487c62 m=10 sigcode=128
autonity  |
autonity  | goroutine 0 [idle]:
autonity  | runtime.abort()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1063 +0x2 fp=0x7fd74dbf91c0 sp=0x7fd74dbf91b8 pc=0x487c62
autonity  | runtime.morestack()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:542 +0x25 fp=0x7fd74dbf91c8 sp=0x7fd74dbf91c0 pc=0x485cc5
autonity  |
autonity  | goroutine 14987542 [running]:
autonity  | runtime.systemstack_switch()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:463 fp=0xc02402ebc8 sp=0xc02402ebc0 pc=0x485be0
autonity  | runtime.throw({0x15c0fa1?, 0xc02402ec30?})
autonity  |     /usr/local/go/src/runtime/panic.go:1043 +0x46 fp=0xc02402ebf8 sp=0xc02402ebc8 pc=0x451ac6
autonity  | runtime.unlock2(0x4e9816?)
autonity  |     /usr/local/go/src/runtime/lock_futex.go:127 +0x7a fp=0xc02402ec18 sp=0xc02402ebf8 pc=0x42665a
autonity  | runtime.unlockWithRank(...)
autonity  |     /usr/local/go/src/runtime/lockrank_off.go:32
autonity  | runtime.unlock(...)
autonity  |     /usr/local/go/src/runtime/lock_futex.go:112
autonity  | runtime.selunlock({0xc02402ee00, 0x2, 0xc089c80000?}, {0xc02402edec, 0x2?, 0x10000000091216f?})
autonity  |     /usr/local/go/src/runtime/select.go:58 +0x73 fp=0xc02402ec40 sp=0xc02402ec18 pc=0x4645d3
autonity  | runtime.selectgo(0xc02402ee00, 0xc02402ede8, 0xc02402ede8?, 0x0, 0x13aa840?, 0x1)
autonity  |     /usr/local/go/src/runtime/select.go:444 +0x1225 fp=0xc02402ed80 sp=0xc02402ec40 pc=0x465985
autonity  | github.com/autonity/autonity/p2p.(*protoRW).WriteMsg(0xc0003fef00, {0x18, 0x22, {0x18c3de0, 0xc022a92960}, {0x0, 0x0, 0x0}, {{0x159e4ee, 0x3}, ...}, ...})
autonity  |     /autonity/p2p/peer.go:463 +0x115 fp=0xc02402ee90 sp=0xc02402ed80 pc=0x9052f5
autonity  | github.com/autonity/autonity/p2p.Send({0x7fd7430becd8, 0xc0003fef00}, 0x8, {0x1365d40?, 0xc05c7fec18?})
autonity  |     /autonity/p2p/message.go:105 +0xb7 fp=0xc02402ef08 sp=0xc02402ee90 pc=0x901b77
autonity  | github.com/autonity/autonity/eth/protocols/eth.(*Peer).sendPooledTransactionHashes(0xc09fdbdb30, {0xc09df9d7a0, 0x1, 0x1})
autonity  |     /autonity/eth/protocols/eth/peer.go:236 +0x97 fp=0xc02402ef58 sp=0xc02402ef08 pc=0xb9d8d7
autonity  | github.com/autonity/autonity/eth/protocols/eth.(*Peer).announceTransactions.func1()
autonity  |     /autonity/eth/protocols/eth/broadcast.go:162 +0x49 fp=0xc02402efe0 sp=0xc02402ef58 pc=0xb94709
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc02402efe8 sp=0xc02402efe0 pc=0x487e01
autonity  | created by github.com/autonity/autonity/eth/protocols/eth.(*Peer).announceTransactions
autonity  |     /autonity/eth/protocols/eth/broadcast.go:161 +0x705
autonity  |
autonity  | goroutine 1 [chan receive, 111 minutes]:
autonity  | runtime.gopark(0xb590cb?, 0x159f029?, 0xb0?, 0x1f?, 0x159f029?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc088dc5818 sp=0xc088dc57f8 pc=0x454836
autonity  | runtime.chanrecv(0xc0003d2ae0, 0x0, 0x1)
autonity  |     /usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc088dc58a8 sp=0xc088dc5818 pc=0x42145d
autonity  | runtime.chanrecv1(0xc0003baf20?, 0xc0000bf180?)
autonity  |     /usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc088dc58d0 sp=0xc088dc58a8 pc=0x420f58
autonity  | github.com/autonity/autonity/node.(*Node).Wait(...)
autonity  |     /autonity/node/node.go:447
autonity  | main.autonity(0xc0003baf20)
autonity  |     /autonity/cmd/autonity/main.go:311 +0x10c fp=0xc088dc5950 sp=0xc088dc58d0 pc=0x11fc60c
autonity  | gopkg.in/urfave/cli%2ev1.HandleAction({0x1357640?, 0x17561d8?}, 0xc00038a000?)
autonity  |     /go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x5a fp=0xc088dc5968 sp=0xc088dc5950 pc=0xb5093a
autonity  | gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000103860, {0xc000040140, 0x14, 0x14})
autonity  |     /go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x71d fp=0xc088dc5f38 sp=0xc088dc5968 pc=0xb4e1dd
autonity  | main.main()
autonity  |     /autonity/cmd/autonity/main.go:240 +0x35 fp=0xc088dc5f80 sp=0xc088dc5f38 pc=0x11fbff5
autonity  | runtime.main()
autonity  |     /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc088dc5fe0 sp=0xc088dc5f80 pc=0x454407
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc088dc5fe8 sp=0xc088dc5fe0 pc=0x487e01
autonity  |
autonity  | goroutine 2 [force gc (idle), 111 minutes]:
autonity  | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006cfb0 sp=0xc00006cf90 pc=0x454836
autonity  | runtime.goparkunlock(...)
autonity  |     /usr/local/go/src/runtime/proc.go:387
autonity  | runtime.forcegchelper()
autonity  |     /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc00006cfe0 sp=0xc00006cfb0 pc=0x454670
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x487e01
autonity  | created by runtime.init.6
autonity  |     /usr/local/go/src/runtime/proc.go:293 +0x25
autonity  |
autonity  | goroutine 3 [GC sweep wait]:
autonity  | runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006d780 sp=0xc00006d760 pc=0x454836
autonity  | runtime.goparkunlock(...)
autonity  |     /usr/local/go/src/runtime/proc.go:387
autonity  | runtime.bgsweep(0x0?)
autonity  |     /usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc00006d7c8 sp=0xc00006d780 pc=0x43e9de
autonity  | runtime.gcenable.func1()
autonity  |     /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00006d7e0 sp=0xc00006d7c8 pc=0x433b86
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006d7e8 sp=0xc00006d7e0 pc=0x487e01
autonity  | created by runtime.gcenable
autonity  |     /usr/local/go/src/runtime/mgc.go:178 +0x6b
autonity  |
autonity  | goroutine 4 [GC scavenge wait]:
autonity  | runtime.gopark(0x2394080?, 0x6bb8bf?, 0x0?, 0x0?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006df70 sp=0xc00006df50 pc=0x454836
autonity  | runtime.goparkunlock(...)
autonity  |     /usr/local/go/src/runtime/proc.go:387
autonity  | runtime.(*scavengerState).park(0x2394080)
autonity  |     /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00006dfa0 sp=0xc00006df70 pc=0x43c8b3
autonity  | runtime.bgscavenge(0x0?)
autonity  |     /usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc00006dfc8 sp=0xc00006dfa0 pc=0x43cea5
autonity  | runtime.gcenable.func2()
autonity  |     /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00006dfe0 sp=0xc00006dfc8 pc=0x433b26
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x487e01
autonity  | created by runtime.gcenable
autonity  |     /usr/local/go/src/runtime/mgc.go:179 +0xaa
autonity  |
autonity  | goroutine 5 [finalizer wait, 111 minutes]:
autonity  | runtime.gopark(0x1a0?, 0x2395b00?, 0xe0?, 0x24?, 0xc00006c770?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006c628 sp=0xc00006c608 pc=0x454836
autonity  | runtime.runfinq()
autonity  |     /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00006c7e0 sp=0xc00006c628 pc=0x432bc7
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x487e01
autonity  | created by runtime.createfing
autonity  |     /usr/local/go/src/runtime/mfinal.go:163 +0x45
autonity  |
autonity  | goroutine 6 [select]:
autonity  | runtime.gopark(0xc00006e798?, 0x2?, 0x3f?, 0xe9?, 0xc00006e794?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006e620 sp=0xc00006e600 pc=0x454836
autonity  | runtime.selectgo(0xc00006e798, 0xc00006e790, 0x0?, 0x0, 0x0?, 0x1)
autonity  |     /usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc00006e760 sp=0xc00006e620 pc=0x464f1e
autonity  | github.com/autonity/autonity/metrics.(*meterArbiter).tick(0x238d040)
autonity  |     /autonity/metrics/meter.go:298 +0x69 fp=0xc00006e7c8 sp=0xc00006e760 pc=0x793169
autonity  | github.com/autonity/autonity/metrics.NewMeter.func2()
autonity  |     /autonity/metrics/meter.go:56 +0x26 fp=0xc00006e7e0 sp=0xc00006e7c8 pc=0x791e46
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006e7e8 sp=0xc00006e7e0 pc=0x487e01
autonity  | created by github.com/autonity/autonity/metrics.NewMeter
autonity  |     /autonity/metrics/meter.go:56 +0xd3
autonity  |
autonity  | goroutine 7 [GC worker (idle)]:
autonity  | runtime.gopark(0x23cc940?, 0x1?, 0x39?, 0x16?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00006ef50 sp=0xc00006ef30 pc=0x454836
autonity  | runtime.gcBgMarkWorker()
autonity  |     /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00006efe0 sp=0xc00006ef50 pc=0x4358f1
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006efe8 sp=0xc00006efe0 pc=0x487e01
autonity  | created by runtime.gcBgMarkStartWorkers
autonity  |     /usr/local/go/src/runtime/mgc.go:1199 +0x25
autonity  |
autonity  | goroutine 18 [GC worker (idle)]:
autonity  | runtime.gopark(0x5da960a9342a?, 0x3?, 0x33?, 0xdc?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000068750 sp=0xc000068730 pc=0x454836
autonity  | runtime.gcBgMarkWorker()
autonity  |     /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000687e0 sp=0xc000068750 pc=0x4358f1
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000687e8 sp=0xc0000687e0 pc=0x487e01
autonity  | created by runtime.gcBgMarkStartWorkers
autonity  |     /usr/local/go/src/runtime/mgc.go:1199 +0x25
autonity  |
autonity  | goroutine 34 [GC worker (idle)]:
autonity  | runtime.gopark(0x5da960a99711?, 0x3?, 0x23?, 0x18?, 0x0?)
autonity  |     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000496750 sp=0xc000496730 pc=0x454836
autonity  | runtime.gcBgMarkWorker()
autonity  |     /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004967e0 sp=0xc000496750 pc=0x4358f1
autonity  | runtime.goexit()
autonity  |     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004967e8 sp=0xc0004967e0 pc=0x487e01
autonity  | created by runtime.gcBgMarkStartWorkers
autonity  |     /usr/local/go/src/runtime/mgc.go:1199 +0x25
autonity  |

**Comment by Jason-Zhangxin-Chen** [comment] 2023-12-27 15:41
Hi @Dedenwrg, thank you so much for reporting this issue! I am investigating the root cause now. BTW, how frequently does it occur in your environment? How did you build this Autonity client? What Golang version was the binary built with?

**Comment by Dedenwrg** [comment] 2023-12-27 16:02
Starts on Tuesday morning, frequency 1-3/day
I'm using a docker image, and just recently my validator got jailed
``
  "registration_block": 208548,
  "total_slashed": 3448861500000000000000,
  "jail_release_block": 1960200,
  "provable_fault_count": 3,
  "state": 2
```

**Comment by Dedenwrg** [comment] 2023-12-28 04:38
Update error
https://pastebin.pl/view/8c0216b5

**Comment by Dedenwrg** [comment] 2024-01-01 07:26
The problem has been resolved, the problem comes from the server I use, the server I use is less responsive, for specifications it meets what is recommended in the document.

**Comment by Jason-Zhangxin-Chen** [comment] 2024-01-02 08:02
> The problem has been resolved, the problem comes from the server I use, the server I use is less responsive, for specifications it meets what is recommended in the document.

Hi @Dedenwrg , thank you for the news, I am reviewing our code and the call trace context of execution, so far I have limited finding around the p2p messaging which cause the panic, usually this kind of runtime errors come from the golang implementation of select statemetn or the underlying I/O interface of OS or HW. However, before close it, let's keep an eyes on it from your setup. Thank you so much for your helps!

**Comment by yazzaoui** [comment] 2024-01-14 16:33
Looking similar to https://github.com/golang/go/issues/62440. It's likely due to a combination of using docker and go 1.21.
The next version of Go seems to have a fix for that and should be available next month.
If you are facing this error again please try deploying without docker. 

There is nothing actionable on our side so I'm closing this issue.

**Closed by yazzaoui** 2024-01-14 16:33 UTC
Labels: type:bug, type:feature, triage
