### ISSUE TITLE
Persist Tendermint state

### ISSUE THREAD

**Issue by IronGauntlets** [autonity/autonity#84] opened 2019-04-26 14:59 UTC
If we don't store tendermint state then nodes can lose important state (such as their locked value) when stopped and started. This can cause the network to get stuck.

**Comment by JekaMas** [comment] 2019-07-02 15:24
Also we need WAL+reply to be able to reproduce any incorrect state after cluster failures.

**Comment by piersy** [comment] 2021-01-11 14:41
Just a note, we should probably just store the tendermint internal state, that's all we should need to avoid nodes sending inconsistent messages.

**Comment by piersy** [comment] 2021-01-14 11:48
Just to clarify this is a scenario we see happening in the `TestTendermintStartStop` tests, in these tests stopping and starting causes the entire tendermint engine to be reconstructed, meaning it loses all state, which sometimes causes the tests to hang.

Consider this scenario, in a nework of size 4, all nodes prevote for a
value, then 2 nodes lock a value and two restart and lose their state
(that they were in the prevote step). When they come back they will
propose new values and the locked nodes will propose the locked value,
niether value can ever be committed because each can garner at most 2
votes.

**Comment by lorenzo-dev1** [comment] 2024-11-06 10:09
superseded by https://github.com/autonity/autonity/issues/969

**Closed by lorenzo-dev1** 2024-11-06 10:09 UTC
Labels: type:feature, priority:2, comp:core
