### ISSUE TITLE
Come up with draft for modular contract design

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#717] opened 2020-10-29 14:39 UTC
#Problem

We know we want to have a flexible approach to managing the customisable on chain behaviour but we don't have a clear idea of how we might break that down in such a way that it is easy to modify and supports as wide a variation of behaviour as possible.

# Implementation

Come up with a draft outlining the various interfaces involved in providing the on chain functionality.

**Comment by aiman** [comment] 2022-04-04 15:28
Closing as duplicate of #387

**Closed by aiman** 2022-04-04 15:28 UTC
Labels: research
